core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('<int:pk>/like_event/', views.like_event, name='like'),
    path('toggle-like/<int:event_id>/', views.toggle_like, name='toggle_like'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
]

eventbrite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    

 ]
  

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Event
from .forms import SignupForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

def index(request):
    events = Event.objects.all()
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'events': events,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })





@login_required
def like_event(request, event_id):
    if request.method == 'POST' and request.is_ajax():
        try:
            event = Event.objects.get(pk=event_id)
            event.is_liked = not event.is_liked
            event.save()
            return JsonResponse({'status': 'success', 'is_liked': event.is_liked})
        except Event.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Event not found'}, status=404)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)






@login_required
def toggle_like(request, event_id):
    if request.method == 'POST' and request.is_ajax():
        event = get_object_or_404(Event, pk=event_id)
        if request.user in event.is_liked.all():
            event.is_liked.remove(request.user)
            is_liked = False
        else:
            event.is_liked.add(request.user)
            is_liked = True
        return JsonResponse({'status': 'success', 'is_liked': is_liked})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | eventBrite</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<nav class="flex justify-between items-center py-6 px-6 border-b border-gray-200">
    <a href="/" class="text-xl font-semibold text-red-500">eventBrite</a>
    <div class="flex flex-grow justify-center"><!-- Add flex-grow and justify-center classes -->
        <a href="#" class="px-6 py-3 text-lg font-semibold text-gray rounded-xl hover:text-gray-700 flex items-center justify-center">
            {% block heading %}{% endblock %}
        </a>
    </div>
    <div class="ml-auto flex">
        {% block rightbuttons %}
        {% endblock %}
        </div>
</nav>

<div class="px-6 py-5">
    {% block content %}
    {% endblock %}
</div>

<footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-200">About</h3>

        <p class="text-lg text-gray-500">Eventbrite is an online platform where you can showcase and discover a myriad of events, attracting audiences and organizers alike to connect and engage seamlessly</p>
    </div>

    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
            <li><a href="#" class="text-lg text-gray-400 hover:text-gray-700">About</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-lg text-gray-400 hover:text-gray-700">Contact</a></li>
            <li><a href="#" class="text-lg text-gray-400 hover:text-gray-700">Privacy policy</a></li>
            <li><a href="#" class="text-lg text-gray-400 hover:text-gray-700">Term of use</a></li>
        </ul>
    </div>
</footer>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}contact{% endblock %}

{% block content %}
<h1> The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}
{% block heading %}Browse Events {% endblock %}
{% block extra_css %}
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}
{% block rightbuttons %}
    {% if request.user.is_authenticated %} 
        <div class="pr-4">
            <a href="{% url 'dashboard:index' %}" class="text-lg text-gray-400 hover:text-gray-700">Dashboard</a>
        </div>
        <div class="pr-4">
            <a href="{% url 'item:new' %}" class="text-lg text-gray-400 hover:text-gray-700">Host an event</a>
        </div>
    {% else %} 
        <div class="pr-4">
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-green-600 text-white rounded-xl hover:bg-green-700">Sign up</a>
        </div>
        <div class="pr-4">
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-black text-white rounded-xl hover:bg-gray-700">Log in</a>
        </div>
    {% endif %}
{% endblock %}


{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <div class="grid grid-cols-3 gap-5">
        {% for event in events %}
            <div class="p-6 bg-white rounded-b-xl flex flex-col">
                <a href="{% url 'item:detail' event.id %}" class="flex items-center">
                    <div>
                        <img src="{{ event.image.url }}" class="rounded-t-xl h-40 w-60 object-cover">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl flex-1">
                        <h2 class="text-2xl">{{ event.event_name }}</h2>
                        <p class="text-gray-500">{{ event.date }} | {{ event.time }}</p>
                        <p class="text-gray-500">{{ event.location }}</p>
                    </div>
                </a>
                <!-- index.html -->
<!-- index.html -->
<button type="button" class="btn btn-light ml-auto pr-5" onclick="toggleLike({{ event.id }})">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi {% if request.user in event.is_liked.all %}bi-heart-fill{% else %}bi-heart{% endif %}" viewBox="0 0 16 16">
        {% if request.user in event.is_liked.all %}
            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314"/>
        {% else %}
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
        {% endif %}
    </svg>
</button>


            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock %}
<script>
    function toggleLike(eventId) {
        fetch(`/toggle-like/${eventId}/`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',  // Add CSRF token for security
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                // Update the interface to reflect the new liked status
                var heartIcon = document.querySelector('#likeButton' + eventId + ' .heart-icon');
                heartIcon.classList.toggle('bi-heart');
                heartIcon.classList.toggle('bi-heart-fill');
            } else {
                console.error('Error toggling like status');
            }
        })
        .catch(error => {
            console.error('Error toggling like status:', error);
        });
    }
</script>

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}
{% block heading %}Login Page{% endblock %}
{% block rightbuttons %} <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-green-600 text-white rounded-xl">Sign up</a>
        {% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>

    </form>
</div>




{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}
{% block rightbuttons %} <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl">Log in</a>
        {% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-green-800 hover:bg-green-400 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}