core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('<int:pk>/like_event/', views.like_event, name='like'),
    path('toggle-like/<int:event_id>/', views.toggle_like, name='toggle_like'),

]

eventbrite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    

 ]
  

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name



class Event(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)  
    event_name = models.CharField(max_length=255)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=255)
    image = models.ImageField(upload_to='event_images')
    is_liked = models.ManyToManyField(User, related_name='liked_events', blank=True)
    user = models.ForeignKey(User, related_name='events', on_delete=models.CASCADE)

    def __str__(self):
        return self.event_name

item/forms.py
from django import forms

from .models import Event

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

from django import forms
from .models import Event

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('category', 'event_name', 'date', 'time', 'location', 'image')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'event_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'date': forms.DateInput(attrs={
                'class': INPUT_CLASSES,
                'type': 'date'
            }),
            'time': forms.TimeInput(attrs={
                'class': INPUT_CLASSES,
                'type': 'time'
            }),
            'location': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('event_name', 'date', 'time', 'location', 'image', 'is_liked')
        widgets = {
            
            'event_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'date': forms.DateInput(attrs={
                'class': INPUT_CLASSES,
                'type': 'date'
            }),
            'time': forms.TimeInput(attrs={
                'class': INPUT_CLASSES,
                'type': 'time'
            }),
            'location': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'is_liked': forms.CheckboxInput(attrs={
                'class': 'form-checkbox h-5 w-5 text-gray-600'
            })
        }

item/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import NewEventForm, EditEventForm
from .models import Category, Event
from django.db.models import Q
def events(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    events = Event.objects.filter(is_liked=True)

    if category_id:
        events = events.filter(category_id=category_id)

    if query:
        events = events.filter(Q(event_name__icontains=query) | Q(description__icontains=query))

    return render(request, 'core/events.html', {
        'events': events,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    event = get_object_or_404(Event, pk=pk)
    related_events = Event.objects.filter(category=event.category, is_liked=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'event': event,
        'related_event': related_events
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewEventForm(request.POST, request.FILES)

        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
    else:
        form = NewEventForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New event',
    })

@login_required
def edit(request, pk):
    event = get_object_or_404(Event, pk=pk, user=request.user)

    if request.method == 'POST':
        form = EditEventForm(request.POST, request.FILES, instance=event)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=event.id)
    else:
        form = EditEventForm(instance=event)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit event',
    })

@login_required
def delete(request, pk):
    event = get_object_or_404(Event, pk=pk, user=request.user)
    event.delete()
    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ event.event_name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ event.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ event.event_name }}</h1>
        <p class="text-gray-500"><strong>Date: </strong>{{ event.date }}</p>
        <p class="text-gray-500"><strong>Time: </strong>{{ event.time }}</p>
        <p class="text-gray-500"><strong>Location: </strong>{{ event.location }}</p>
    
        {% if event.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ event.description }}
            </p>
        {% endif %}

        {% if request.user == event.user %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your event!</p>

                <a href="{% url 'item:edit' event.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' event.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}  
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Contact organizer</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related events</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for related_event in related_events %}
            <div>
                <a href="{% url 'event:detail' related_event.id %}">
                    <div>
                        <img src="{{ related_event.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ related_event.event_name }}</h2>
                        <p class="text-gray-500">Date: {{ related_event.date }}</p>
                        <p class="text-gray-500">Time: {{ related_event.time }}</p>
                        <p class="text-gray-500">Location: {{ related_event.location }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

                </div>
            
        </div>
    </div>
</div>

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}